title: "Jan Roddy"
email: jan.roddy.e@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Computer Science master's student focusing on Computer Science Education, Web Programming, and UI/UX
baseurl: "/portfolio"
url: "http://janroddy.github/potfolio.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: janroddy

# Build settings
permalink: pretty
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
